### ISSUE TITLE
CCU REST API Deprecation

### ISSUE THREAD

**Issue by synedra** [beathan/django-akamai#4]
Hello,

I just wanted to give a heads up that the CCU REST API is deprecated and will be at EOL fairly soon. Please consider making a new version that uses the new OPEN Authentication and CCU interface. Note that very soon there will be a version which purges in 5 seconds.

https://community.akamai.com/community/developer/blog/2015/08/20/getting-started-with-the-v2-open-ccu-api

Thanks,
Kirsten

**Comment by acdha** [comment]
Thanks — I guess they haven't gotten around to notifying customers yet. I'll work on that tomorrow.

**Comment by acdha** [comment]
@synedra I finally got around to working on #5. I'm still waiting on my account to be provisioned with the true fast purge API (I currently have access to it only through Luna) but have confirmed that the new endpoints seamlessly fall back to the older ~5 minute purge behaviour.

**Comment by synedra** [comment]
You should be able to activate it in property manager and use the v3 API with it going forward.  It should be available for any account type, it's just not activated by default for each property.

Thanks,
Kirsten

**Comment by acdha** [comment]
@synedra All of the docs reference a “Fast Purge Transition” app which isn't present in my view and there doesn't appear to be anything in the property config either. I opened a case (F-CS-2123577) asking about it earlier in case we have some stale legacy account settings.

**Comment by synedra** [comment]
Oh, it's possible that it's not available for config manager properties, I'm not sure.

Let me; know if you need us to push from our end at anyone.

Thanks so much,
Kirsten

**Comment by acdha** [comment]
Thanks - I'll let the normal support process roll for awhile first.
